History works, added Quality Gates rule

diff --git a/.github/workflows/run_tests_pipeline.yml b/.github/workflows/run_tests_pipeline.yml
--- a/.github/workflows/run_tests_pipeline.yml
+++ b/.github/workflows/run_tests_pipeline.yml
@@ -152,7 +152,7 @@ jobs:
           node-version: '24.19.0'
 
       # 6. Генерируем отчет во ВРЕМЕННУЮ папку отчета
-      - name: Generate Allure Report
+      - name: Generate Allure Report & Check Quality Gate
         env:
           ALLURE_HISTORY_PATH: ${{ github.workspace }}/combined-allure-results/history.jsonl
         run: |
@@ -176,6 +176,18 @@ jobs:
               echo "No log file found!"
             fi
             exit 1
+          }
+          
+          # 3. Запускаем проверку Quality Gate на основе сгенерированных результатов
+          echo "🛡️ Checking Quality Gate rules..."
+          npx allure quality-gate combined-allure-results --config allurerc.js || {
+            echo "❌ Quality Gate failed! The build is unstable."
+          
+            # (Опционально) Попытка вывести логи при падении ворот качества
+            LATEST_LOG=$(ls -t /home/runner/.allure/logs/*.log 2>/dev/null | head -1)
+            [ -n "$LATEST_LOG" ] && cat "$LATEST_LOG"
+          
+            exit 1 # Роняем шаг GitHub Actions
           }
 
       # 7. Скачиваем Swagger отчет (например, от chrome) для публикации
