Правка конфига под Quality Gates

diff --git a/.github/workflows/run_tests_pipeline.yml b/.github/workflows/run_tests_pipeline.yml
--- a/.github/workflows/run_tests_pipeline.yml
+++ b/.github/workflows/run_tests_pipeline.yml
@@ -101,7 +101,7 @@ jobs:
           npm uninstall allure
           npm install allure --no-save
 
-      # 1. Создаем структуру для истории, если её нет
+      # 1. Чистим мусор
       - name: Prepare history directory
         run: |
           echo "🧹 Cleaning all Allure artifacts from previous runs..."
@@ -217,30 +217,30 @@ jobs:
           fi
 
       # 9 Переносим ГОТОВЫЙ отчет со всеми плагинами в дерево истории средствами bash
-      - name: Move Generated Report to History Tree
-        run: |
-          # Создаем изолированную директорию для текущего запуска
-          mkdir -p allure-history/${{ github.run_number }}
+        #- name: Move Generated Report to History Tree
+          #run: |
+          ## Создаем изолированную директорию для текущего запуска
+          #mkdir -p allure-history/${{ github.run_number }}
           
           # Переносим всё содержимое (включая awesome и swagger)
           # Bash сделает это атомарно, Node.js процессы уже завершены и папки не заблокированы
-          cp -R allure-report/* allure-history/${{ github.run_number }}/
+          #cp -R allure-report/* allure-history/${{ github.run_number }}/
           
           # Проверяем результат в целевой папке
-          if [ -f "allure-history/${{ github.run_number }}/index.html" ]; then
-            echo "✅ Report successfully moved to history"
-          else
-            echo "❌ Report migration failed"
-            exit 1
-          fi
+          #if [ -f "allure-history/${{ github.run_number }}/index.html" ]; then
+          # echo "✅ Report successfully moved to history"
+          #else
+          # echo "❌ Report migration failed"
+          # exit 1
+        #fi
 
       # 10. Сохраняем историю как артефакт для следующего запуска
-      - name: Save Allure history
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-history
-          path: allure-history/
-          retention-days: 10
+        #- name: Save Allure history
+        #uses: actions/upload-artifact@v4
+          #with:
+          #name: allure-history
+          #path: allure-history/
+        #retention-days: 10
 
       # debug
       - name: Copy new history for artifact
